set(__QT_DEPLOY_TARGET_CGAL_Qt6_moc_and_resources_FILE /home/frfr/Documents/Τημμυ/Διπλωματική/shared/Advancing front/libCGAL_Qt6_moc_and_resources.a)
set(__QT_DEPLOY_TARGET_CGAL_Qt6_moc_and_resources_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_Advancing_front_FILE /home/frfr/Documents/Τημμυ/Διπλωματική/shared/Advancing front/Advancing_front)
set(__QT_DEPLOY_TARGET_Advancing_front_TYPE EXECUTABLE)
