set(__QT_DEPLOY_TARGET_CGAL_Qt6_moc_and_resources_FILE /home/frfr/Documents/Τημμυ/Διπλωματική/shared/Kinetic/libCGAL_Qt6_moc_and_resources.a)
set(__QT_DEPLOY_TARGET_CGAL_Qt6_moc_and_resources_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_Kinetic_FILE /home/frfr/Documents/Τημμυ/Διπλωματική/shared/Kinetic/Kinetic)
set(__QT_DEPLOY_TARGET_Kinetic_TYPE EXECUTABLE)
